name: cafe24-js-cd
on:
  push:
    branches: [ main ]
jobs:
  cafe24-deploy-codepush:
    name: Deploy Codepush 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "14"
      - name: Install packages
        run: npm ci
      - name: Login AppCenter
        run: ./node_modules/.bin/appcenter login --token $APPCENTER_TOKEN
        env:
          APPCENTER_TOKEN: ${{ secrets.APPCENTER_TOKEN }}
      - name: Deploy codepush update (Android)
        run: npm run code-push-production-android
