name: cafe24-js-cd
on:
  push:
    branches:
      - "main"
    paths:
      - "cafe24/**"
jobs:
  cafe24-deploy-codepush:
    name: Deploy Codepush 
    runs-on: ubuntu-latest
    env:
      PROJECT_PATH: cafe24
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "14"
      - name: Install packages
        run: npm ci
        working-directory: ${{ env.PROJECT_PATH }}
      - name: Login AppCenter
        run: ./node_modules/.bin/appcenter login --token $APPCENTER_TOKEN
        working-directory: ${{ env.PROJECT_PATH }}
        env:
          APPCENTER_TOKEN: ${{ secrets.APPCENTER_TOKEN }}
      - name: Deploy codepush update (Android)
        run: npm run code-push-production-android
        working-directory: ${{ env.PROJECT_PATH }}